name: CI

on:
  push:
    branches: [ main ]
    paths:
      - "index.js"
      - "test.js"
      - "package.json"
      - ".github/workflows/**"

  pull_request:
    paths:
      - "index.js"
      - "test.js"
      - "package.json"
      - ".github/workflows/**"

  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      node-version: "20"
